# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='admin.proto',
  package='pb',
  syntax='proto3',
  serialized_options=_b('Z\004.;pb'),
  serialized_pb=_b('\n\x0b\x61\x64min.proto\x12\x02pb\"%\n\x07\x41uthReq\x12\x0e\n\x06\x63ookie\x18\x01 \x01(\t\x12\n\n\x02ID\x18\x02 \x01(\x04\"&\n\x07\x41uthAck\x12\x1b\n\x04\x63ode\x18\x01 \x01(\x0e\x32\r.pb.ErrorCode*\x13\n\tErrorCode\x12\x06\n\x02OK\x10\x00\x42\x06Z\x04.;pbb\x06proto3')
)

_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='pb.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=98,
  serialized_end=117,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODE)

ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
OK = 0



_AUTHREQ = _descriptor.Descriptor(
  name='AuthReq',
  full_name='pb.AuthReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cookie', full_name='pb.AuthReq.cookie', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ID', full_name='pb.AuthReq.ID', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=56,
)


_AUTHACK = _descriptor.Descriptor(
  name='AuthAck',
  full_name='pb.AuthAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='pb.AuthAck.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=96,
)

_AUTHACK.fields_by_name['code'].enum_type = _ERRORCODE
DESCRIPTOR.message_types_by_name['AuthReq'] = _AUTHREQ
DESCRIPTOR.message_types_by_name['AuthAck'] = _AUTHACK
DESCRIPTOR.enum_types_by_name['ErrorCode'] = _ERRORCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthReq = _reflection.GeneratedProtocolMessageType('AuthReq', (_message.Message,), dict(
  DESCRIPTOR = _AUTHREQ,
  __module__ = 'admin_pb2'
  # @@protoc_insertion_point(class_scope:pb.AuthReq)
  ))
_sym_db.RegisterMessage(AuthReq)

AuthAck = _reflection.GeneratedProtocolMessageType('AuthAck', (_message.Message,), dict(
  DESCRIPTOR = _AUTHACK,
  __module__ = 'admin_pb2'
  # @@protoc_insertion_point(class_scope:pb.AuthAck)
  ))
_sym_db.RegisterMessage(AuthAck)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
