# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import admin_pb2 as admin__pb2


class NodeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Auth = channel.unary_unary(
        '/pb.Node/Auth',
        request_serializer=admin__pb2.AuthReq.SerializeToString,
        response_deserializer=admin__pb2.AuthAck.FromString,
        )


class NodeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Auth(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NodeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Auth': grpc.unary_unary_rpc_method_handler(
          servicer.Auth,
          request_deserializer=admin__pb2.AuthReq.FromString,
          response_serializer=admin__pb2.AuthAck.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pb.Node', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
