# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import admin_pb2 as admin__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='pb',
  syntax='proto3',
  serialized_options=_b('Z\004.;pb'),
  serialized_pb=_b('\n\rservice.proto\x12\x02pb\x1a\x0b\x61\x64min.proto2(\n\x04Node\x12 \n\x04\x41uth\x12\x0b.pb.AuthReq\x1a\x0b.pb.AuthAckB\x06Z\x04.;pbb\x06proto3')
  ,
  dependencies=[admin__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_NODE = _descriptor.ServiceDescriptor(
  name='Node',
  full_name='pb.Node',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=34,
  serialized_end=74,
  methods=[
  _descriptor.MethodDescriptor(
    name='Auth',
    full_name='pb.Node.Auth',
    index=0,
    containing_service=None,
    input_type=admin__pb2._AUTHREQ,
    output_type=admin__pb2._AUTHACK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NODE)

DESCRIPTOR.services_by_name['Node'] = _NODE

# @@protoc_insertion_point(module_scope)
