// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_OK ErrorCode = 0
)

var ErrorCode_name = map[int32]string{
	0: "OK",
}

var ErrorCode_value = map[string]int32{
	"OK": 0,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{0}
}

type AuthReq struct {
	Cookie               string   `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"`
	ID                   uint64   `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthReq) Reset()         { *m = AuthReq{} }
func (m *AuthReq) String() string { return proto.CompactTextString(m) }
func (*AuthReq) ProtoMessage()    {}
func (*AuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{0}
}

func (m *AuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthReq.Unmarshal(m, b)
}
func (m *AuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthReq.Marshal(b, m, deterministic)
}
func (m *AuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthReq.Merge(m, src)
}
func (m *AuthReq) XXX_Size() int {
	return xxx_messageInfo_AuthReq.Size(m)
}
func (m *AuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthReq proto.InternalMessageInfo

func (m *AuthReq) GetCookie() string {
	if m != nil {
		return m.Cookie
	}
	return ""
}

func (m *AuthReq) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type AuthAck struct {
	Code                 ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=pb.ErrorCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AuthAck) Reset()         { *m = AuthAck{} }
func (m *AuthAck) String() string { return proto.CompactTextString(m) }
func (*AuthAck) ProtoMessage()    {}
func (*AuthAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{1}
}

func (m *AuthAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthAck.Unmarshal(m, b)
}
func (m *AuthAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthAck.Marshal(b, m, deterministic)
}
func (m *AuthAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthAck.Merge(m, src)
}
func (m *AuthAck) XXX_Size() int {
	return xxx_messageInfo_AuthAck.Size(m)
}
func (m *AuthAck) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthAck.DiscardUnknown(m)
}

var xxx_messageInfo_AuthAck proto.InternalMessageInfo

func (m *AuthAck) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_OK
}

func init() {
	proto.RegisterEnum("pb.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterType((*AuthReq)(nil), "pb.AuthReq")
	proto.RegisterType((*AuthAck)(nil), "pb.AuthAck")
}

func init() {
	proto.RegisterFile("admin.proto", fileDescriptor_73a7fc70dcc2027c)
}

var fileDescriptor_73a7fc70dcc2027c = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4c, 0xc9, 0xcd,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x32, 0xe4, 0x62, 0x77,
	0x2c, 0x2d, 0xc9, 0x08, 0x4a, 0x2d, 0x14, 0x12, 0xe3, 0x62, 0x4b, 0xce, 0xcf, 0xcf, 0xce, 0x4c,
	0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x84, 0xf8, 0xb8, 0x98, 0x3c, 0x5d, 0x24,
	0x98, 0x14, 0x18, 0x35, 0x58, 0x82, 0x98, 0x3c, 0x5d, 0x94, 0x74, 0x20, 0x5a, 0x1c, 0x93, 0xb3,
	0x85, 0x14, 0xb9, 0x58, 0x92, 0xf3, 0x53, 0x20, 0x1a, 0xf8, 0x8c, 0x78, 0xf5, 0x0a, 0x92, 0xf4,
	0x5c, 0x8b, 0x8a, 0xf2, 0x8b, 0x9c, 0xf3, 0x53, 0x52, 0x83, 0xc0, 0x52, 0x5a, 0xc2, 0x5c, 0x9c,
	0x70, 0x21, 0x21, 0x36, 0x2e, 0x26, 0x7f, 0x6f, 0x01, 0x06, 0x27, 0xb6, 0x28, 0x16, 0x3d, 0xeb,
	0x82, 0xa4, 0x24, 0x36, 0xb0, 0x43, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x47, 0x99, 0x60,
	0xa5, 0x97, 0x00, 0x00, 0x00,
}
